import { createHmac, timingSafeEqual } from "node:crypto";

/**
 * One-click unsubscribe (CAN-SPAM) has to work without an authenticated
 * session, so the link itself carries a token proving it was generated by
 * us for this exact user — reuses AUTH_SECRET (already a signing secret in
 * this app) rather than introducing a new one just for this.
 */
function secret(): string {
  const s = process.env.AUTH_SECRET;
  if (!s) throw new Error("AUTH_SECRET is not set");
  return s;
}

export function unsubscribeToken(userId: string): string {
  return createHmac("sha256", secret()).update(userId).digest("hex");
}

export function verifyUnsubscribeToken(userId: string, token: string): boolean {
  const expected = unsubscribeToken(userId);
  const a = Buffer.from(expected, "hex");
  const b = Buffer.from(token, "hex");
  if (a.length !== b.length) return false;
  return timingSafeEqual(a, b);
}
